###
GET http://localhost:5153/games

###
POST http://localhost:5153/games
Content-Type: application/json

{
    "title": "The Legend of Zelda: Breath of the Wild",
    "genre": "Action-adventure",
    "releaseDate": "2017-03-03"
}

###
DELETE http://localhost:5153/games/1
